using UnityEngine;
using UnityEngine.SceneManagement;

public class FinDeNiveau : MonoBehaviour
{
    private void OnTriggerEnter2D(Collider2D collision)
    {
        if(collision.gameObject.CompareTag("Player"))
        {
            Debug.Log("Félicitation, le niveau est terminé.");
            GameManager.Instance.SaveData();

            if (SceneManager.GetActiveScene().name != "Level3")
            {
                GameManager.Instance.PlayerData.AjouterNiveau();
                GameManager.Instance.SaveData();
                if (SceneManager.GetActiveScene().name == "Level1")
                {
                    SceneManager.LoadScene("Level2");
                } 
                else if (SceneManager.GetActiveScene().name == "Level2")
                {
                    SceneManager.LoadScene("Level3");
                }

            }
            else
            {
                SceneManager.LoadScene("MainMenu");
            }
        }
    }
}
